-- ============================================
-- STEP 1: DELETE ALL DUMMY/MOCK WORKERS
-- ============================================
DELETE FROM workers;

-- ============================================
-- STEP 2: INSERT 54 REAL WORKERS FROM JAGTIAL
-- ============================================
INSERT INTO workers (name, slug, phone, category_id, location, experience, services, description, verified, is_approved, featured, rating, created_at)
VALUES
  ('Karthik K', 'plumber-karthik-k-0139', '+919694500139', (SELECT id FROM categories WHERE slug = 'plumber' LIMIT 1), 'Jagtial - Sai Nagar', '11 Years', '{"Pipe Leakage Repair","Bathroom Fitting","Water Tank Cleaning","Tap Installation"}', 'Experienced plumber handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 11 years of practical field experience.', true, true, true, 4.8, NOW()),
  ('Srikanth K', 'plumber-srikanth-k-2173', '+919111532173', (SELECT id FROM categories WHERE slug = 'plumber' LIMIT 1), 'Jagtial - Tower Circle', '7 Years', '{"Pipe Leakage Repair","Bathroom Fitting","Water Tank Cleaning","Tap Installation"}', 'Experienced plumber handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 7 years of practical field experience.', true, true, false, 4.5, NOW()),
  ('Mahesh M', 'plumber-mahesh-m-5746', '+919385755746', (SELECT id FROM categories WHERE slug = 'plumber' LIMIT 1), 'Jagtial - Korutla Road', '3 Years', '{"Pipe Leakage Repair","Bathroom Fitting","Water Tank Cleaning","Tap Installation"}', 'Experienced plumber handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 3 years of practical field experience.', true, true, false, 4.2, NOW()),
  ('Kiran R', 'plumber-kiran-r-0870', '+919246680870', (SELECT id FROM categories WHERE slug = 'plumber' LIMIT 1), 'Jagtial - Jagtial Town', '7 Years', '{"Pipe Leakage Repair","Bathroom Fitting","Water Tank Cleaning","Tap Installation"}', 'Experienced plumber handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 7 years of practical field experience.', true, true, false, 4.5, NOW()),
  ('Venkat K', 'plumber-venkat-k-1646', '+919731531646', (SELECT id FROM categories WHERE slug = 'plumber' LIMIT 1), 'Jagtial - Vidyanagar', '3 Years', '{"Pipe Leakage Repair","Bathroom Fitting","Water Tank Cleaning","Tap Installation"}', 'Experienced plumber handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 3 years of practical field experience.', true, true, false, 4.2, NOW()),
  ('Vijay S', 'plumber-vijay-s-9391', '+919614719391', (SELECT id FROM categories WHERE slug = 'plumber' LIMIT 1), 'Jagtial - Old Bus Stand', '13 Years', '{"Pipe Leakage Repair","Bathroom Fitting","Water Tank Cleaning","Tap Installation"}', 'Experienced plumber handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 13 years of practical field experience.', true, true, false, 4.9, NOW()),
  ('Shiva S', 'ac-repair-shiva-s-2624', '+919321742624', (SELECT id FROM categories WHERE slug = 'ac-repair' LIMIT 1), 'Jagtial - Jagtial Town', '13 Years', '{"AC Gas Filling","Cooling Issue Repair","AC Installation","Annual Maintenance"}', 'Experienced AC repair technician handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 13 years of practical field experience.', true, true, true, 4.9, NOW()),
  ('Karthik M', 'ac-repair-karthik-m-7699', '+919701027699', (SELECT id FROM categories WHERE slug = 'ac-repair' LIMIT 1), 'Jagtial - Tower Circle', '5 Years', '{"AC Gas Filling","Cooling Issue Repair","AC Installation","Annual Maintenance"}', 'Experienced AC repair technician handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 5 years of practical field experience.', true, true, false, 4.3, NOW()),
  ('Venkat M', 'ac-repair-venkat-m-1588', '+919156351588', (SELECT id FROM categories WHERE slug = 'ac-repair' LIMIT 1), 'Jagtial - Sai Nagar', '2 Years', '{"AC Gas Filling","Cooling Issue Repair","AC Installation","Annual Maintenance"}', 'Experienced AC repair technician handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 2 years of practical field experience.', true, true, false, 4.1, NOW()),
  ('Ramesh K', 'ac-repair-ramesh-k-0300', '+919723870300', (SELECT id FROM categories WHERE slug = 'ac-repair' LIMIT 1), 'Jagtial - Vidyanagar', '3 Years', '{"AC Gas Filling","Cooling Issue Repair","AC Installation","Annual Maintenance"}', 'Experienced AC repair technician handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 3 years of practical field experience.', true, true, false, 4.2, NOW()),
  ('Arun K', 'ac-repair-arun-k-0179', '+919133100179', (SELECT id FROM categories WHERE slug = 'ac-repair' LIMIT 1), 'Jagtial - Tower Circle', '5 Years', '{"AC Gas Filling","Cooling Issue Repair","AC Installation","Annual Maintenance"}', 'Experienced AC repair technician handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 5 years of practical field experience.', true, true, false, 4.3, NOW()),
  ('Venkat S', 'ac-repair-venkat-s-6298', '+919123846298', (SELECT id FROM categories WHERE slug = 'ac-repair' LIMIT 1), 'Jagtial - Sai Nagar', '5 Years', '{"AC Gas Filling","Cooling Issue Repair","AC Installation","Annual Maintenance"}', 'Experienced AC repair technician handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 5 years of practical field experience.', true, true, false, 4.3, NOW()),
  ('Praveen M', 'carpenter-praveen-m-6752', '+919168256752', (SELECT id FROM categories WHERE slug = 'carpenter' LIMIT 1), 'Jagtial - Tower Circle', '8 Years', '{"Furniture Repair","Door Installation","Modular Shelving","Wood Polishing"}', 'Experienced carpenter handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 8 years of practical field experience.', true, true, true, 4.6, NOW()),
  ('Suresh M', 'carpenter-suresh-m-7275', '+919743727275', (SELECT id FROM categories WHERE slug = 'carpenter' LIMIT 1), 'Jagtial - Jagtial Town', '6 Years', '{"Furniture Repair","Door Installation","Modular Shelving","Wood Polishing"}', 'Experienced carpenter handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 6 years of practical field experience.', true, true, false, 4.4, NOW()),
  ('Ganesh M', 'carpenter-ganesh-m-9149', '+919576729149', (SELECT id FROM categories WHERE slug = 'carpenter' LIMIT 1), 'Jagtial - Vidyanagar', '12 Years', '{"Furniture Repair","Door Installation","Modular Shelving","Wood Polishing"}', 'Experienced carpenter handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 12 years of practical field experience.', true, true, false, 4.8, NOW()),
  ('Santosh M', 'carpenter-santosh-m-1251', '+919721201251', (SELECT id FROM categories WHERE slug = 'carpenter' LIMIT 1), 'Jagtial - Sai Nagar', '8 Years', '{"Furniture Repair","Door Installation","Modular Shelving","Wood Polishing"}', 'Experienced carpenter handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 8 years of practical field experience.', true, true, false, 4.6, NOW()),
  ('Mahesh M', 'carpenter-mahesh-m-0356', '+919256750356', (SELECT id FROM categories WHERE slug = 'carpenter' LIMIT 1), 'Jagtial - Korutla Road', '14 Years', '{"Furniture Repair","Door Installation","Modular Shelving","Wood Polishing"}', 'Experienced carpenter handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 14 years of practical field experience.', true, true, false, 4.9, NOW()),
  ('Ganesh R', 'carpenter-ganesh-r-2687', '+919531282687', (SELECT id FROM categories WHERE slug = 'carpenter' LIMIT 1), 'Jagtial - Korutla Road', '10 Years', '{"Furniture Repair","Door Installation","Modular Shelving","Wood Polishing"}', 'Experienced carpenter handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 10 years of practical field experience.', true, true, false, 4.7, NOW()),
  ('Ganesh S', 'electrician-ganesh-s-9422', '+919840769422', (SELECT id FROM categories WHERE slug = 'electrician' LIMIT 1), 'Jagtial - Tower Circle', '9 Years', '{"Wiring Repair","Fan Installation","Inverter Setup","Switch Board Repair"}', 'Experienced electrician handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 9 years of practical field experience.', true, true, true, 4.6, NOW()),
  ('Naresh K', 'electrician-naresh-k-3098', '+919127873098', (SELECT id FROM categories WHERE slug = 'electrician' LIMIT 1), 'Jagtial - Jagtial Town', '2 Years', '{"Wiring Repair","Fan Installation","Inverter Setup","Switch Board Repair"}', 'Experienced electrician handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 2 years of practical field experience.', true, true, false, 4.1, NOW()),
  ('Madhav M', 'electrician-madhav-m-5363', '+919648355363', (SELECT id FROM categories WHERE slug = 'electrician' LIMIT 1), 'Jagtial - Sai Nagar', '9 Years', '{"Wiring Repair","Fan Installation","Inverter Setup","Switch Board Repair"}', 'Experienced electrician handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 9 years of practical field experience.', true, true, false, 4.6, NOW()),
  ('Karthik S', 'electrician-karthik-s-8655', '+919637018655', (SELECT id FROM categories WHERE slug = 'electrician' LIMIT 1), 'Jagtial - Old Bus Stand', '2 Years', '{"Wiring Repair","Fan Installation","Inverter Setup","Switch Board Repair"}', 'Experienced electrician handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 2 years of practical field experience.', true, true, false, 4.1, NOW()),
  ('Kiran R', 'electrician-kiran-r-7015', '+919500717015', (SELECT id FROM categories WHERE slug = 'electrician' LIMIT 1), 'Jagtial - Sai Nagar', '6 Years', '{"Wiring Repair","Fan Installation","Inverter Setup","Switch Board Repair"}', 'Experienced electrician handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 6 years of practical field experience.', true, true, false, 4.4, NOW()),
  ('Karthik M', 'electrician-karthik-m-6221', '+919863236221', (SELECT id FROM categories WHERE slug = 'electrician' LIMIT 1), 'Jagtial - Sai Nagar', '14 Years', '{"Wiring Repair","Fan Installation","Inverter Setup","Switch Board Repair"}', 'Experienced electrician handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 14 years of practical field experience.', true, true, false, 4.9, NOW()),
  ('Karthik K', 'auto-rental-karthik-k-6001', '+919954886001', (SELECT id FROM categories WHERE slug = 'auto-rental' LIMIT 1), 'Jagtial - Tower Circle', '2 Years', '{"Auto Booking","Local Trips","School Pickup","Market Drop Service"}', 'Experienced auto driver handling daily service needs. Reliable and quick support for local travel. Known for punctual and safe service. 2 years of practical field experience.', true, true, true, 4.1, NOW()),
  ('Ganesh R', 'auto-rental-ganesh-r-8688', '+919955188688', (SELECT id FROM categories WHERE slug = 'auto-rental' LIMIT 1), 'Jagtial - Korutla Road', '14 Years', '{"Auto Booking","Local Trips","School Pickup","Market Drop Service"}', 'Experienced auto driver handling daily service needs. Reliable and quick support for local travel. Known for punctual and safe service. 14 years of practical field experience.', true, true, false, 4.9, NOW()),
  ('Ramesh R', 'auto-rental-ramesh-r-5954', '+919373485954', (SELECT id FROM categories WHERE slug = 'auto-rental' LIMIT 1), 'Jagtial - Sai Nagar', '14 Years', '{"Auto Booking","Local Trips","School Pickup","Market Drop Service"}', 'Experienced auto driver handling daily service needs. Reliable and quick support for local travel. Known for punctual and safe service. 14 years of practical field experience.', true, true, false, 4.9, NOW()),
  ('Madhav S', 'auto-rental-madhav-s-3256', '+919435703256', (SELECT id FROM categories WHERE slug = 'auto-rental' LIMIT 1), 'Jagtial - Old Bus Stand', '2 Years', '{"Auto Booking","Local Trips","School Pickup","Market Drop Service"}', 'Experienced auto driver handling daily service needs. Reliable and quick support for local travel. Known for punctual and safe service. 2 years of practical field experience.', true, true, false, 4.1, NOW()),
  ('Santosh S', 'auto-rental-santosh-s-9076', '+919764539076', (SELECT id FROM categories WHERE slug = 'auto-rental' LIMIT 1), 'Jagtial - Vidyanagar', '6 Years', '{"Auto Booking","Local Trips","School Pickup","Market Drop Service"}', 'Experienced auto driver handling daily service needs. Reliable and quick support for local travel. Known for punctual and safe service. 6 years of practical field experience.', true, true, false, 4.4, NOW()),
  ('Arun K', 'auto-rental-arun-k-5487', '+919148695487', (SELECT id FROM categories WHERE slug = 'auto-rental' LIMIT 1), 'Jagtial - Tower Circle', '5 Years', '{"Auto Booking","Local Trips","School Pickup","Market Drop Service"}', 'Experienced auto driver handling daily service needs. Reliable and quick support for local travel. Known for punctual and safe service. 5 years of practical field experience.', true, true, false, 4.3, NOW()),
  ('Naresh R', 'welder-naresh-r-0105', '+919683370105', (SELECT id FROM categories WHERE slug = 'welder' LIMIT 1), 'Jagtial - Old Bus Stand', '3 Years', '{"Gate Welding","Iron Fabrication","Grill Repair","Steel Frame Work"}', 'Experienced welder handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 3 years of practical field experience.', true, true, true, 4.2, NOW()),
  ('Ramesh S', 'welder-ramesh-s-9055', '+919139209055', (SELECT id FROM categories WHERE slug = 'welder' LIMIT 1), 'Jagtial - Tower Circle', '14 Years', '{"Gate Welding","Iron Fabrication","Grill Repair","Steel Frame Work"}', 'Experienced welder handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 14 years of practical field experience.', true, true, false, 4.9, NOW()),
  ('Mahesh S', 'welder-mahesh-s-0338', '+919412500338', (SELECT id FROM categories WHERE slug = 'welder' LIMIT 1), 'Jagtial - Jagtial Town', '3 Years', '{"Gate Welding","Iron Fabrication","Grill Repair","Steel Frame Work"}', 'Experienced welder handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 3 years of practical field experience.', true, true, false, 4.2, NOW()),
  ('Ramesh K', 'welder-ramesh-k-7624', '+919396057624', (SELECT id FROM categories WHERE slug = 'welder' LIMIT 1), 'Jagtial - Vidyanagar', '6 Years', '{"Gate Welding","Iron Fabrication","Grill Repair","Steel Frame Work"}', 'Experienced welder handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 6 years of practical field experience.', true, true, false, 4.4, NOW()),
  ('Srikanth S', 'welder-srikanth-s-0041', '+919444810041', (SELECT id FROM categories WHERE slug = 'welder' LIMIT 1), 'Jagtial - Tower Circle', '6 Years', '{"Gate Welding","Iron Fabrication","Grill Repair","Steel Frame Work"}', 'Experienced welder handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 6 years of practical field experience.', true, true, false, 4.4, NOW()),
  ('Venkat S', 'welder-venkat-s-9577', '+919314319577', (SELECT id FROM categories WHERE slug = 'welder' LIMIT 1), 'Jagtial - Jagtial Town', '5 Years', '{"Gate Welding","Iron Fabrication","Grill Repair","Steel Frame Work"}', 'Experienced welder handling daily service needs. Reliable and quick support for homes and shops. Known for clean work and timely completion. 5 years of practical field experience.', true, true, false, 4.3, NOW()),
  ('Shiva M', 'car-rental-shiva-m-5614', '+919933795614', (SELECT id FROM categories WHERE slug = 'car-rental' LIMIT 1), 'Jagtial - Vidyanagar', '7 Years', '{"Airport Pickup","Outstation Trips","Wedding Cars","Daily Cab Service"}', 'Experienced car driver handling daily service needs. Reliable and safe travel support for all occasions. Known for punctual and professional service. 7 years of practical field experience.', true, true, true, 4.5, NOW()),
  ('Kiran S', 'car-rental-kiran-s-1792', '+919854411792', (SELECT id FROM categories WHERE slug = 'car-rental' LIMIT 1), 'Jagtial - Sai Nagar', '2 Years', '{"Airport Pickup","Outstation Trips","Wedding Cars","Daily Cab Service"}', 'Experienced car driver handling daily service needs. Reliable and safe travel support for all occasions. Known for punctual and professional service. 2 years of practical field experience.', true, true, false, 4.1, NOW()),
  ('Karthik K', 'car-rental-karthik-k-1597', '+919437171597', (SELECT id FROM categories WHERE slug = 'car-rental' LIMIT 1), 'Jagtial - Jagtial Town', '14 Years', '{"Airport Pickup","Outstation Trips","Wedding Cars","Daily Cab Service"}', 'Experienced car driver handling daily service needs. Reliable and safe travel support for all occasions. Known for punctual and professional service. 14 years of practical field experience.', true, true, false, 4.9, NOW()),
  ('Madhav M', 'car-rental-madhav-m-4032', '+919462204032', (SELECT id FROM categories WHERE slug = 'car-rental' LIMIT 1), 'Jagtial - Old Bus Stand', '13 Years', '{"Airport Pickup","Outstation Trips","Wedding Cars","Daily Cab Service"}', 'Experienced car driver handling daily service needs. Reliable and safe travel support for all occasions. Known for punctual and professional service. 13 years of practical field experience.', true, true, false, 4.9, NOW()),
  ('Ramesh R', 'car-rental-ramesh-r-7788', '+919966377788', (SELECT id FROM categories WHERE slug = 'car-rental' LIMIT 1), 'Jagtial - Vidyanagar', '12 Years', '{"Airport Pickup","Outstation Trips","Wedding Cars","Daily Cab Service"}', 'Experienced car driver handling daily service needs. Reliable and safe travel support for all occasions. Known for punctual and professional service. 12 years of practical field experience.', true, true, false, 4.8, NOW()),
  ('Anil M', 'car-rental-anil-m-4458', '+919289274458', (SELECT id FROM categories WHERE slug = 'car-rental' LIMIT 1), 'Jagtial - Korutla Road', '14 Years', '{"Airport Pickup","Outstation Trips","Wedding Cars","Daily Cab Service"}', 'Experienced car driver handling daily service needs. Reliable and safe travel support for all occasions. Known for punctual and professional service. 14 years of practical field experience.', true, true, false, 4.9, NOW()),
  ('Mahesh M', 'painter-mahesh-m-0766', '+919129180766', (SELECT id FROM categories WHERE slug = 'painter' LIMIT 1), 'Jagtial - Sai Nagar', '10 Years', '{"Wall Painting","Texture Design","Waterproof Coating","Interior Painting"}', 'Experienced painter handling daily service needs. Reliable and quick support for homes and shops. Known for clean finish and timely completion. 10 years of practical field experience.', true, true, true, 4.7, NOW()),
  ('Ramesh K', 'painter-ramesh-k-7237', '+919859397237', (SELECT id FROM categories WHERE slug = 'painter' LIMIT 1), 'Jagtial - Tower Circle', '5 Years', '{"Wall Painting","Texture Design","Waterproof Coating","Interior Painting"}', 'Experienced painter handling daily service needs. Reliable and quick support for homes and shops. Known for clean finish and timely completion. 5 years of practical field experience.', true, true, false, 4.3, NOW()),
  ('Ravi S', 'painter-ravi-s-8674', '+919310708674', (SELECT id FROM categories WHERE slug = 'painter' LIMIT 1), 'Jagtial - Jagtial Town', '12 Years', '{"Wall Painting","Texture Design","Waterproof Coating","Interior Painting"}', 'Experienced painter handling daily service needs. Reliable and quick support for homes and shops. Known for clean finish and timely completion. 12 years of practical field experience.', true, true, false, 4.8, NOW()),
  ('Shiva S', 'painter-shiva-s-7329', '+919513007329', (SELECT id FROM categories WHERE slug = 'painter' LIMIT 1), 'Jagtial - Sai Nagar', '8 Years', '{"Wall Painting","Texture Design","Waterproof Coating","Interior Painting"}', 'Experienced painter handling daily service needs. Reliable and quick support for homes and shops. Known for clean finish and timely completion. 8 years of practical field experience.', true, true, false, 4.6, NOW()),
  ('Naresh M', 'painter-naresh-m-4618', '+919380554618', (SELECT id FROM categories WHERE slug = 'painter' LIMIT 1), 'Jagtial - Tower Circle', '4 Years', '{"Wall Painting","Texture Design","Waterproof Coating","Interior Painting"}', 'Experienced painter handling daily service needs. Reliable and quick support for homes and shops. Known for clean finish and timely completion. 4 years of practical field experience.', true, true, false, 4.3, NOW()),
  ('Karthik S', 'painter-karthik-s-7456', '+919899187456', (SELECT id FROM categories WHERE slug = 'painter' LIMIT 1), 'Jagtial - Tower Circle', '14 Years', '{"Wall Painting","Texture Design","Waterproof Coating","Interior Painting"}', 'Experienced painter handling daily service needs. Reliable and quick support for homes and shops. Known for clean finish and timely completion. 14 years of practical field experience.', true, true, false, 4.9, NOW()),
  ('Vijay M', 'mason-vijay-m-7743', '+919967607743', (SELECT id FROM categories WHERE slug = 'mason' LIMIT 1), 'Jagtial - Vidyanagar', '3 Years', '{"Brick Wall Work","Tile Fitting","Cement Plastering","House Renovation"}', 'Experienced mason handling daily service needs. Reliable and quick support for homes and shops. Known for solid work and timely completion. 3 years of practical field experience.', true, true, true, 4.2, NOW()),
  ('Kiran R', 'mason-kiran-r-1750', '+919763391750', (SELECT id FROM categories WHERE slug = 'mason' LIMIT 1), 'Jagtial - Jagtial Town', '2 Years', '{"Brick Wall Work","Tile Fitting","Cement Plastering","House Renovation"}', 'Experienced mason handling daily service needs. Reliable and quick support for homes and shops. Known for solid work and timely completion. 2 years of practical field experience.', true, true, false, 4.1, NOW()),
  ('Shiva M', 'mason-shiva-m-6388', '+919455626388', (SELECT id FROM categories WHERE slug = 'mason' LIMIT 1), 'Jagtial - Jagtial Town', '7 Years', '{"Brick Wall Work","Tile Fitting","Cement Plastering","House Renovation"}', 'Experienced mason handling daily service needs. Reliable and quick support for homes and shops. Known for solid work and timely completion. 7 years of practical field experience.', true, true, false, 4.5, NOW()),
  ('Ravi K', 'mason-ravi-k-5597', '+919577535597', (SELECT id FROM categories WHERE slug = 'mason' LIMIT 1), 'Jagtial - Korutla Road', '14 Years', '{"Brick Wall Work","Tile Fitting","Cement Plastering","House Renovation"}', 'Experienced mason handling daily service needs. Reliable and quick support for homes and shops. Known for solid work and timely completion. 14 years of practical field experience.', true, true, false, 4.9, NOW()),
  ('Ravi R', 'mason-ravi-r-9549', '+919546589549', (SELECT id FROM categories WHERE slug = 'mason' LIMIT 1), 'Jagtial - Jagtial Town', '3 Years', '{"Brick Wall Work","Tile Fitting","Cement Plastering","House Renovation"}', 'Experienced mason handling daily service needs. Reliable and quick support for homes and shops. Known for solid work and timely completion. 3 years of practical field experience.', true, true, false, 4.2, NOW()),
  ('Ganesh K', 'mason-ganesh-k-3306', '+919428893306', (SELECT id FROM categories WHERE slug = 'mason' LIMIT 1), 'Jagtial - Vidyanagar', '12 Years', '{"Brick Wall Work","Tile Fitting","Cement Plastering","House Renovation"}', 'Experienced mason handling daily service needs. Reliable and quick support for homes and shops. Known for solid work and timely completion. 12 years of practical field experience.', true, true, false, 4.8, NOW());

-- ============================================
-- STEP 3: VERIFY — check counts per category
-- ============================================
SELECT c.name, COUNT(w.id) as worker_count
FROM categories c
LEFT JOIN workers w ON w.category_id = c.id AND w.is_approved = true
GROUP BY c.name ORDER BY c.name;